@Web = http://localhost:8080
@Email=
@Password=
@BearerToken=

//Catalogue
// Tạo catalogue
POST {{Web}}/catalogues/create-catalogue
Content-Type: application/json

{
    "name": "nội thất nhà bếp"
}

###
// Lấy danh sách catalogue
GET {{Web}}/catalogues/get-all-catalogues


###
// chỉnh sửa catalogue
# với 1 là id của catalogue (int) 
PUT {{Web}}/catalogues/update-catalogue/2
Content-Type: application/json

{
    "name": "nội thất văn phòng"
}

////////////////////////////////////Product////////////////////////////////////
###
//tạo product
POST {{Web}}/products/create-product
Content-Type: application/json

{
    "name": "tủ gỗ",
    "description": "aaaaaaa",
    "warranty": 1,
    "catalogueId": 1
}

###
//update product
//số 1 là id của product
PUT {{Web}}/products/update-product/1 
Content-Type: application/json

{
    "name": "bàn ghế",
    "description": "aaaa",
    "warranty": 1,
    "catalogueId": null
}

###
//ngưng bán một sản phẩm
PUT {{Web}}/products/stop-selling/1
Content-Type: application/json


###
//danh sách sản phẩm
GET {{Web}}/products/get-all-products

////////////////////////////////////ProductVariant////////////////////////////////////

###
//tạo variant cho product
//với 1 là productId
POST {{Web}}/variants/create-variant/1
Content-Type: application/json

{
    "sku": "sgkfndf",
    "price": 19000,
    "buyingPrice": 100000,
    "color": "pink",
    "size": "dài 30cm, rộng 25cm"
}

###
//sửa variant
//với 1 là id của variant
PUT {{Web}}/variants/update-variant/2
Content-Type: application/json

{
    "sku": "aaaa",
    "price": 9000,
    "buyingPrice": 120000,
    "color": "green",
    "size": "dài 35cm, rộng 45cm"
}

###
//lấy danh sách product variant của 1 product
//với 1 là id của product
GET {{Web}}/variants/get-all-variants/1

###
//lấy danh sách variant
GET {{Web}}/variants

###
//chi tiết của 1 product variant
GET {{Web}}/variants/get-variant/1

###
//lấy product variant của 1 product
GET {{Web}}/products/get-product/1

////////////////////////////////////Goods Receipt////////////////////////////////////

###
//tạo hóa đơn thanh toán
//const = quantity * price của một variant, tui nghĩ cái const này front xử lý vì 
//còn phải hiện ra giá trong đơn thanh toán
POST {{Web}}/goods-receipt/create-goods-receipt
Content-Type: application/json

{
    "shipping": 1000,
    "GoodsReceiptDetailsData": [
        {"variantId": 1, "quantity": 10, "cost": 1000},
        {"variantId": 2, "quantity": 10, "cost": 1000},
        {"variantId": 1, "quantity": 10, "cost": 1000},
        {"variantId": 2, "quantity": 10, "cost": 1000}
    ],
    "totalCost": 10000,
    "providerId": 1
}

###
//lấy danh sách hóa đơn thanh toán
GET {{Web}}/goods-receipt/get-all-goods-receipts

###
GET  {{Web}}/goods-receipt/get-goods-receipt/3

###
//sửa hóa đơn thanh toán
//với 1 là id của hóa đơn
PUT {{Web}}/goods-receipt/update-goods-receipt/1
Content-Type: application/json

{
    "shipping": 1000,
    "GoodsReceiptDetailsData": [
        {"variantId": 1, "quantity": 20, "cost": 2000},
        {"variantId": 2, "quantity": 10, "cost": 1000},
        {"variantId": 1, "quantity": 40, "cost": 4000},
        {"variantId": 2, "quantity": 20, "cost": 2000}
    ],
    "totalCost": 10000
}

###
//accept hóa đơn thanh toán (xác nhận đã nhận đc hàng)
//sau khi xác nhận thì inventory sẽ tăng lên
//khi inventory tăng lên thì sẽ tự cập nhật lại số lượng sản phẩm trong kho
//khi đó available, total sẽ xét, nếu khác 0 thì status thành in stock
//với 1 là id của hóa đơn
PUT {{Web}}/goods-receipt/accept-goods-receipt/1

###
//từ chối hóa đơn thanh toán (hủy hoặc không nhận hàng do hàng không đạt yêu cầu)
//với 1 là id của hóa đơn
PUT {{Web}}/goods-receipt/reject-goods-receipt/1

////////////////////////////////////Invoice////////////////////////////////////
###
POST {{Web}}/invoices/create-invoice
Content-Type: application/json

{
    "InvoiceDetailsData": [
        {"variantId": 1, "quantity": 3, "cost": 1000},
        {"variantId": 2, "quantity": 2, "cost": 1000},
        {"variantId": 1, "quantity": 6, "cost": 1000},
        {"variantId": 2, "quantity": 2, "cost": 1000}
    ],
    "totalCost": 10000
}

###
//lấy danh sách hóa đơn thanh toán
GET {{Web}}/invoices/get-all-invoices

###
GET  {{Web}}/invoices/get-invoice/1

###
//sửa hóa đơn thanh toán
PUT {{Web}}/invoices/update-invoice/2
Content-Type: application/json

{
    "InvoiceDetailsData": [
        {"variantId": 1, "quantity": 5, "cost": 2000},
        {"variantId": 2, "quantity": 2, "cost": 1000},
        {"variantId": 1, "quantity": 2, "cost": 4000},
        {"variantId": 2, "quantity": 7, "cost": 2000}
    ],
    "totalCost": 10000
}

###
//accept hóa đơn thanh toán (xác nhận đã nhận đc hàng)
//sau khi xác nhận thì inventory sẽ tăng lên
//khi inventory tăng lên thì sẽ tự cập nhật lại số lượng sản phẩm trong kho
//khi đó available, total sẽ xét, nếu khác 0 thì status thành in stock
//với 1 là id của hóa đơn
PUT {{Web}}/invoices/accept-invoice/1

###
//từ chối hóa đơn thanh toán (hủy hoặc không nhận hàng do hàng không đạt yêu cầu)
//với 1 là id của hóa đơn
PUT {{Web}}/invoices/reject-invoice/1

////////////////////////////////////Provider////////////////////////////////////
###
//tạo nhà cung cấp
POST {{Web}}/providers/create-provider
Content-Type: application/json

{
    "name": "công ty TNHH xyz",
    "address": "123 đường ABC",
    "phone": "0123456789",
    "email": "abc@gmail.com",
    "president": "Nguyễn Văn A"
}

###
//lấy danh sách nhà cung cấp
GET {{Web}}/providers/get-all-providers

###
//lấy danh sách nhà cung cấp còn hoạt động
GET {{Web}}/providers/get-all-active-providers

###
// tra cứu nhà cung cấp
GET {{Web}}/providers/get-provider/1

###
//sửa nhà cung cấp
//với 1 là id của nhà cung cấp
PUT {{Web}}/providers/update-provider/1
Content-Type: application/json

{
    "name": "công ty TNHH ABC",
    "address": "123 đường ABC",
    "phone": "0123456789",
    "email": "updatedAbc@gmail.com",
    "president": "Nguyễn Văn B"
}

###
//xóa nhà cung cấp
//với 1 là id của nhà cung cấp
DELETE {{Web}}/providers/delete-provider/1

////////////////////////////////////Customer////////////////////////////////////
###
//tạo khách hàng
POST {{Web}}/customers/create-customer
Content-Type: application/json

{
    "name": "Nguyễn Văn B",
    "phone": "0123456789",
    "email": "nguyenvanb@gmail.com"
}

###
//lấy danh sách khách hàng
GET {{Web}}/customers/get-all-customers

###
// tra cứu khách hàng
GET {{Web}}/customers/get-customer/2

###
//sửa khách hàng
//với 1 là id của khách hàng
PUT {{Web}}/customers/update-customer/1
Content-Type: application/json

{
    "name": "Nguyễn Văn C",
    "phone": "0123456789",
    "email": "nguyenvanc@gmail.com"
}

###
DELETE {{Web}}/customers/delete-customer/1

////////////////////////////////////Staff////////////////////////////////////
//thêm nhân viên
###
POST {{Web}}/staffs/create-staff
Content-Type: application/json

{
    "fullname": "Nguyễn Văn A",
    "birth": "1999-12-20",
    "gender": "male",
    "idNumber": "0123456789",
    "startDate": "2020-08-30",
    "phone": "0123456789",
    "email": "nguyenvana@gmail.com",
    "role": 3
}

###
PUT {{Web}}/staffs/update-staff/1
Content-Type: application/json

{
    "fullname": "Nguyễn Văn B",
    "birth": "1999-12-20",
    "gender": "male",
    "idNumber": "0123456789",
    "startDate": "2020-08-30",
    "phone": "0123456789",
    "email": "nguyenvana@gmail.com"
}

###
GET {{Web}}/staffs/get-all-staffs

###
GET {{Web}}/staffs/get-staff/1

###
DELETE {{Web}}/staffs/delete-staff/1
////////////////////////////////////Authentication////////////////////////////////////
###
POST {{Web}}/login
Content-Type: application/json

{
    "username": "SaleStaff0001",
    "password": "SaleStaff0001"
}

////////////////////////////////////Promotion////////////////////////////////////
###
GET {{Web}}/promotion/get-all-promotions


###
// Lấy thông tin của 1 promotion + danh sách các sản phẩm(variant) + % giảm giá thông qua ID của promotion
GET {{Web}}/promotion/:id

###
// Lấy thông tin của 1 promotion đang diễn ra + danh sách các sản phẩm(variant) + % giảm giá thông qua ngày
GET {{Web}}/promotion/date=YYYY-MM-DD

###
// Tạo mới một promotion
POST {{Web}}/promotion/create-promotion
Content-Type: application/json

{
    "name": "promotion 1",
    "description": "description for promotion 1",
    "startDate": "2024-11-19",
    "finishDate": "2024-11-21",
    "promotionProducts": [
        {
            "variantId": 1,
            "discount": 10
        },
        {
            "variantId": 2,
            "discount": 15
        }
    ]
}

###
// Cập nhật promotion
PUT {{Web}}/promotion/update-promotion

Content-Type: application/json
{
    "id": 1,
    "name": "promotion 1: updated",
    "description": "description for promotion 1: updated",
    "startDate": "2024-11-19",
    "finishDate": "2024-11-22",
    "promotionProducts": [
        {
            "variantId": 1,
            "discount": 10
        },
        {
            "variantId": 2,
            "discount": 15
        }
    ]
}

###
// Xoá promotion

DELETE {{Web}}/promotion/delete-promotion/:id

###
// Stop promotion

PATCH {{Web}}/promotion/stop-promotion

Content-Type: application/json
{
    "id": 1
}